### ISSUE TITLE
[Dev] clean up the branches and home party @ master.

### ISSUE THREAD

**Issue by minhoryang** [EurekaKR/font-eureka#10]

**Comment by minhoryang** [comment]
@JimJeon can you handle this?

**Comment by JimJeon** [comment]
@minhoryang Ok, I'll try!

**Comment by JimJeon** [comment]
BTW what do you mean, "home party"?

**Comment by minhoryang** [comment]
@JimJeon ["Jarvis, initiate the House Party Protocol."](https://www.youtube.com/watch?v=gK0IGjBssJ4)

**Comment by minhoryang** [comment]
Already merged
